.vscode/settings.json, README.md, lib/apiGateway/validate.js, lib/apiGateway/validate.test.js, lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js, package.json
Fixes #11
Note to @horike37 : 
If `authorizationType` is set to `CUSTOM` I'm not creating the authorizer resource (If that is what you meant in your comment to #11).
I think it might be better if one defines the authorizer explicitly, but maybe we can wait for more use cases.
I'm actually using `AWS_IAM` (I wrote a [plugin](https://github.com/erezrokah/serverless-plugin-api-gateway-integrations) before noticing this one exists...).
=> Feature: add support for adding authorization

.vscode/settings.json, README.md, lib/apiGateway/validate.js, lib/apiGateway/validate.test.js, lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js, package.json
Fixes #15 
See more details in the issue.
This is branched out from this pr #14
=> Feature: add sqs request parameters

README.md
fixes a `README` copy paste error introduced in https://github.com/horike37/serverless-apigateway-service-proxy/pull/16
=> Add missing 'DataType' request parameter mapping in README

__tests__/integration/kinesis/multiple-integrations/service/serverless.yml, __tests__/integration/kinesis/multiple-integrations/tests.js, __tests__/integration/kinesis/single-integration/service/serverless.yml, __tests__/integration/kinesis/single-integration/tests.js, __tests__/integration/sqs/multiple-integrations/service/serverless.yml, __tests__/integration/sqs/multiple-integrations/tests.js, __tests__/integration/sqs/single-integration/service/serverless.yml, __tests__/integration/sqs/single-integration/tests.js, __tests__/utils.js, lib/package/kinesis/compileIamRoleToKinesis.js, lib/package/kinesis/compileIamRoleToKinesis.test.js, lib/package/sqs/compileIamRoleToSqs.js, lib/package/sqs/compileIamRoleToSqs.test.js, package.json
Fixes #17 
Per @theburningmonk suggestion in the issue above and [here](https://github.com/horike37/serverless-apigateway-service-proxy/pull/19#issuecomment-521639080).
Took longer than expected as I added more integrations tests and ran into a stability issue with the tests - they were passing all the time when running with one worker, but failing sometimes with multiple workers.
I believe this is due to the `serverless deploy` command running from the root directory for all the tests, so the `.serverless` directory got deleted/overwritten occasionally.
The solution was to set a different working directory for each test using the `cwd` option of the `execSync` function.
I searched for a way to change the default `.serverless` directory but from looking at the framework code it seems …
=> Fix: limit sqs,kinesis permissions

README.md, __tests__/integration/kinesis/multiple-integrations/service/serverless.yml, __tests__/integration/kinesis/multiple-integrations/tests.js, __tests__/integration/kinesis/single-integration/tests.js, lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, package.json
- Put whole body parameters into Kinesis record.
- Changed how to set partitionkey like the following:
- By default, using aws request_id
- `partitionKey` param is hardcorded, using it
- `pathParam` is set to `partitionKey` param, using pathparameter in request URL path
- `bodyParam` is set, using body parameter in request
- `queryStringParam` is set, using query in request URL
=> feat: change default behavior of kinesis proxy

README.md, __tests__/integration/sns/custom-mapping-template/service/serverless.yml, __tests__/integration/sns/custom-mapping-template/tests.js, __tests__/integration/sns/multiple-integrations/service/serverless.yml, __tests__/integration/sns/multiple-integrations/tests.js, __tests__/integration/sns/single-integration/service/serverless.yml, __tests__/integration/sns/single-integration/tests.js, __tests__/utils.js, lib/apiGateway/validate.js, lib/apiGateway/validate.test.js, lib/index.js, lib/index.test.js, lib/package/sns/compileIamRoleToSns.js, lib/package/sns/compileIamRoleToSns.test.js, lib/package/sns/compileMethodsToSns.js, lib/package/sns/compileMethodsToSns.test.js, lib/package/sns/compileSnsServiceProxy.js, lib/package/sns/schema.js, lib/package/sns/validateSnsServiceProxy.js, lib/package/sns/validateSnsServiceProxy.test.js, package-lock.json, package.json
Fixes #10
* This is mostly a reproduction of the process described [here](https://www.alexdebrie.com/posts/aws-api-gateway-service-proxy/#creating-the-service-proxy-integration).
* I removed some [unnecessary](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/) `-X POST`  from the readme.
* Integrations tests will validate the content of the published message by attaching an SQS queue to the SNS topic (I'm using https://github.com/erezrokah/aws-testing-library, so if you don't want to introduce another dependency I can remove the content validation or implement the functionally to validate it as a part of this plugin - also I don't want to feel like I'm promoting my lib for no reason).
* Added a specific integration test to validate the custom mapping template
* Fixed some …
=> Feature: add sns support

lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
All `Fn::Join` intrinsic functions was replaced with `Fn::Sub` in this plugin.
=> Refactor: Use Fn::Sub function instead of Fn::Join

README.md, __tests__/integration/common/accept-parameters/service/serverless.yml, __tests__/integration/common/accept-parameters/tests.js, lib/apiGateway/schema.js, lib/apiGateway/validate.test.js, lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/s3/compileMethodsToS3.js, lib/package/s3/compileMethodsToS3.test.js, lib/package/sns/compileMethodsToSns.js, lib/package/sns/compileMethodsToSns.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
Fixes #44 
@Vlaaaaaaad if you'd like to test it you can install directly from my branch:
```json
"dependencies": {
...
"serverless-apigateway-service-proxy": "git://github.com/erezrokah/serverless-apigateway-service-proxy.git#feat/allow_passing_method_request_parameters"
}
```
=> feat: support customizing method request parameters

README.md, lib/apiGateway/schema.js, lib/package/s3/compileMethodsToS3.js, lib/package/s3/compileMethodsToS3.test.js, package.json
We recently faced a problem with the serverless proxy integration, namely when the s3 has a couple of folders and the folders should be mapped via path parameters. We found out that the solution to this would be to slightly adjust this plugin (by making the path override dynamic with fallback to the default functionality)
The main change was made in `lib/package/s3/compileMethodsToS3.js`:
```js
let pather = '{bucket}/{object}'
if (_.has(http, 'pathoverride')) {
pather = '{bucket}/' + http.pathoverride
}
const integration = {
IntegrationHttpMethod: httpMethod,
Type: 'AWS',
Credentials: roleArn,
Uri: {
'Fn::Sub': ['arn:aws:apigateway:${AWS::Region}:s3:path/' + pather, {}]
},
PassthroughBehavior: 'WHEN_NO_MATCH',
RequestParameters: _.merge(requestParams, http.requestParameters)
}
```
This …
=> Adding Dynamic Path Override

lib/apiGateway/schema.js, lib/apiGateway/validate.test.js
Fixes https://github.com/horike37/serverless-apigateway-service-proxy/issues/51
See the end of the comment here https://github.com/horike37/serverless-apigateway-service-proxy/issues/51#issuecomment-556983282
On the reason `authorizerId` was disallowed for cognito until now.
=> fix(cognito_auth): allow setting authorizerId for cognito

package-lock.json, package.json
This fixes #57 .  common-tags isn't just a dev dependency, but needs to be installed as a dependency for users of your package.  
Thanks!
=> fix: common-tags appears to be package dependency, not just a dev dep

README.md, lib/apiGateway/schema.js, lib/apiGateway/validate.test.js, lib/package/dynamodb/compileMethodsToDynamodb.test.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/s3/compileMethodsToS3.test.js, lib/package/sns/compileMethodsToSns.test.js, lib/package/sqs/compileMethodsToSqs.test.js
Currently, Serverless allows API Key validation by using a field called private. This plugin also does but it doesn't allow it to pass the validation with this error:
```
child "sqs" fails because ["private" is not allowed]
```
This PR just to allow private field to pass the validation.
=> Allow Private Field

README.md, lib/apiGateway/schema.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
Adds support for response templates for SQS.
Supports the simplified response structure supported for Kinesis (see #54) but also allows more-complex integration response mappings.
Related to #80, #86.
=> feat(sqs): add response template support for sqs

README.md, lib/apiGateway/schema.js, lib/apiGateway/validate.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
Allows the addition of `request.template.<content-type>` to `serverless.yml` under `apiGatewayServiceProxies`.
Changes the approach to passing basic `Action` and `MessageBody` values by passing them in the POST request payload instead of via querystrings. This means that the prior default `RequestParameters` have been replaced with a single default which sets the `Content-Type` to `application/x-www-form-urlencoded`.
An example config which satisfies the requirements for an SQS FIFO queue follows.
Given a request payload of:
```json
{
"event_type": "message",
"event_id": "ABC123",
"message": "Hello!"
}
```
Then the following config inside `serverless.yml`:
```yaml
apiGatewayServiceProxies:
- sqs:
path: /{version}/event/receiver
method: post
queueName:
Fn::GetAtt:
- eventQueue
- …
```
=> feat(sqs): add request template support for sqs

README.md, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
A different approach to backward compatibility. Basically allows existing implementations to work exactly the same way.
If there is a custom request body specified, we do things differently. Firstly, we don't use any query string values if they are present (they need to be passed into the body if there is a body). We also disable pass-through of headers from the client. These also have to bo explicitly passed through via the body.
Fixes tests which broke during merge of #86.
Allows #94 to be closed without merge.
=> feat(sqs): full backwards compatibility for sqs without a custom body

lib/package/dynamodb/compileIamRoleToDynamodb.js, lib/package/dynamodb/compileIamRoleToDynamodb.test.js, lib/package/dynamodb/compileMethodsToDynamodb.js, lib/package/dynamodb/compileMethodsToDynamodb.test.js, lib/package/eventbridge/compileIamRoleToEventBridge.js, lib/package/eventbridge/compileIamRoleToEventBridge.test.js, lib/package/eventbridge/compileMethodsToEventBridge.js, lib/package/eventbridge/compileMethodsToEventBridge.test.js, lib/package/kinesis/compileIamRoleToKinesis.js, lib/package/kinesis/compileIamRoleToKinesis.test.js, lib/package/kinesis/compileMethodsToKinesis.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/s3/compileIamRoleToS3.js, lib/package/s3/compileIamRoleToS3.test.js, lib/package/s3/compileMethodsToS3.js, lib/package/s3/compileMethodsToS3.test.js, lib/package/sns/compileIamRoleToSns.js, lib/package/sns/compileIamRoleToSns.test.js, lib/package/sns/compileMethodsToSns.js, lib/package/sns/compileMethodsToSns.test.js, lib/package/sqs/compileIamRoleToSqs.js, lib/package/sqs/compileIamRoleToSqs.test.js, lib/package/sqs/compileMethodsToSqs.js, lib/package/sqs/compileMethodsToSqs.test.js
Previously the plugin constructed ARNs assuming that they will all be in
`arn:aws:...`, which would cause failures when deploying to an alternate
AWS partition.
This changes the plugin to use the AWS::Partition pseudo-parameter to
ensure that the local partition value is used.
Fixes #85 .
=> fix: use AWS::Partition pseudo-parameter in ARNs

README.md, lib/apiGateway/schema.js, lib/package/sns/compileMethodsToSns.js, lib/package/sns/compileMethodsToSns.test.js
Hi, I've produced a Pull Request to add support for custom response mappings for SNS. This is very similar in practice to the SQS implementation so I've leant heavily on that for this implementation.
I'd appreciate any feedback and your thoughts on whether it makes a sensible addition to the project.
Thanks
Related to: #89
=> feat(sns): add support for custom response mappings

.travis.yml, lib/apiGateway/schema.js, lib/apiGateway/validate.test.js, lib/package/dynamodb/compileMethodsToDynamodb.test.js
Adding custom RequestTemplates was disallowed by the schema definition for the dynamo proxy. I've added to that schema and added a new test for the schema change. 
But, there was already an [`Object.assign` call](https://github.com/serverless-operations/serverless-apigateway-service-proxy/blob/v1.11.1/lib/package/dynamodb/compileMethodsToDynamodb.js#L100)  to merge the package-default RequestTemplate with any template defined in the serverless.yaml file. So ... either this was an easy implementation or I've missed some detail as to why the approach in my PR is invalid. So, I just added a test to check the custom request template would be applied.
Let me know if I've missed something which stops support of the custom request templates here.
If not, I'd like to add docs for these before any …
=> feat(dynamodb): custom request mapping templates

lib/apiGateway/methods.test.js, lib/apiGateway/validate.test.js, lib/index.test.js, lib/package/dynamodb/compileIamRoleToDynamodb.test.js, lib/package/dynamodb/compileMethodsToDynamodb.test.js, lib/package/eventbridge/compileEventBridgeServiceProxy.test.js, lib/package/eventbridge/compileIamRoleToEventBridge.test.js, lib/package/eventbridge/compileMethodsToEventBridge.test.js, lib/package/kinesis/compileIamRoleToKinesis.test.js, lib/package/kinesis/compileKinesisServiceProxy.test.js, lib/package/kinesis/compileMethodsToKinesis.test.js, lib/package/s3/compileIamRoleToS3.test.js, lib/package/s3/compileMethodsToS3.test.js, lib/package/s3/compileS3ServiceProxy.test.js, lib/package/sns/compileIamRoleToSns.test.js, lib/package/sns/compileMethodsToSns.test.js, lib/package/sns/compileSnsServiceProxy.test.js, lib/package/sqs/compileIamRoleToSqs.test.js, lib/package/sqs/compileMethodsToSqs.test.js, lib/package/sqs/compileSqsServiceProxy.test.js, lib/utils.test.js, package-lock.json, package.json
Potential fix for the issue https://github.com/serverless-operations/serverless-apigateway-service-proxy/issues/108
1. Upgraded sls framework to `2.69.1`
2. Moved the SLS framework to peer and dev dependencies. 
3. Replaced all the references of `serverless/lib/plugins/aws/provider/awsProvider` to `serverless/lib/plugins/aws/provider`
4. All the tests on local works fine.
=> Serverless framework upgrade to v2.x

lib/apiGateway/schema.js, lib/apiGateway/validate.test.js
This adds the `request` property to the EventBridge schema object. I have also added a test that fails if the `request` property is removed from the EventBridge schema.
The test would fail with:
```
281 passing (584ms)
1 failing
1) #validateServiceProxies()
eventbridge
should throw error if eventbridge request is missing the template property:
AssertionError: expected [Function] to throw error including 'child "eventbridge" fails because [ch…' but got 'child "eventbridge" fails because ["r…'
+ expected - actual
-child "eventbridge" fails because ["request" is not allowed]
+child "eventbridge" fails because [child "request" fails because [child "template" fails because ["template" is required]]]
at Context.<anonymous> (lib/apiGateway/validate.test.js:2290:87)
at processImmediate …
```
=> fix: add request property to EventBridge schema

README.md
I can confirm that the the extra `\` was actually not valid and was causing my response to default to the last template in the list.
=> Fixes selectionPattern documentation
